export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOG_OUT = 'LOG_OUT'
export const LOAD_PROFILE = 'LOAD_PROFILE'

export const HOME_VOLUME_SUCCESS = 'HOME_VOLUME_SUCCESS'
export const HOME_VOLUME_FAIL = 'HOME_VOLUME_FAIL'
export const HOME_VOLUME_REQUEST = 'HOME_VOLUME_REQUEST'

export const SEARCHED_REQUEST = 'SEARCHED_REQUEST'
export const SEARCHED_SUCCESS = 'SEARCHED_SUCCESS'
export const SEARCHED_FAIL = 'SEARCHED_FAIL'

export const MODEL_REQUEST = 'MODEL_REQUEST'
export const MODEL_SUCCESS = 'MODEL_SUCCESS'
export const MODEL_FAIL = 'MODEL_FAIL'
